# Generated by Django 4.1.7 on 2023-03-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('user_name', models.CharField(blank=True, max_length=256, null=True)),
                ('is_bot', models.BooleanField(blank=True, default=False, null=True)),
                ('steep', models.CharField(blank=True, max_length=128, null=True)),
                ('last_query', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
