# Generated by Django 4.1.7 on 2023-04-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('user_name', models.CharField(blank=True, max_length=256, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('steep', models.CharField(blank=True, max_length=128, null=True)),
                ('last_query', models.TextField(blank=True, null=True)),
                ('inline_log', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=128)),
                ('car_number', models.CharField(max_length=128)),
                ('tex_passport_number', models.CharField(max_length=128)),
                ('year', models.CharField(blank=True, max_length=128, null=True)),
                ('car_color', models.CharField(blank=True, max_length=128, null=True)),
                ('car_transmission', models.CharField(blank=True, max_length=128, null=True)),
                ('car_km', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarsLessee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessee_first_name', models.CharField(max_length=128, verbose_name='Ijarachi Ismi')),
                ('lessee_last_name', models.CharField(max_length=128, verbose_name='Ijarachi Familiyasi')),
                ('lessee_passport_seria', models.CharField(max_length=128, verbose_name='Passport raqami')),
                ('lessee_phone_one', models.CharField(max_length=128, verbose_name='Assosiy telefon')),
                ('lessee_phone_two', models.CharField(blank=True, max_length=128, null=True, verbose_name="Qo'shimcha telefon")),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('starting_price', models.CharField(max_length=256, verbose_name='Boshlangich summa')),
                ('monthly_payment', models.CharField(max_length=258, verbose_name='Oylik tulov')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cars')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField()),
                ('month_payment', models.CharField(max_length=256)),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.carslessee')),
            ],
        ),
        migrations.CreateModel(
            name='LesseeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.carslessee')),
            ],
        ),
        migrations.CreateModel(
            name='CarImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cars')),
            ],
        ),
    ]
