# Generated by Django 4.1.7 on 2023-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='inline_log',
            field=models.JSONField(default={}, null=True),
        ),
    ]
