# Generated by Django 4.1.7 on 2023-03-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_bot_user_is_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=128)),
                ('car_number', models.CharField(max_length=128)),
                ('tex_passport_number', models.CharField(max_length=128)),
                ('year', models.CharField(blank=True, max_length=128, null=True)),
                ('car_color', models.CharField(blank=True, max_length=128, null=True)),
                ('car_transmission', models.CharField(blank=True, max_length=128, null=True)),
                ('car_km', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars_lessee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessee_first_name', models.CharField(max_length=128)),
                ('lessee_last_name', models.CharField(max_length=128)),
                ('lessee_passport_seria', models.CharField(max_length=128)),
                ('lessee_birth_date', models.CharField(blank=True, max_length=128, null=True)),
                ('lessee_phone_one', models.CharField(max_length=128)),
                ('lessee_phone_two', models.CharField(blank=True, max_length=128, null=True)),
                ('lessee_adress', models.TextField()),
                ('lessee_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
