# Generated by Django 4.1.7 on 2023-03-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cars_cars_lessee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cars')),
            ],
        ),
        migrations.CreateModel(
            name='CarsLessee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessee_first_name', models.CharField(max_length=128)),
                ('lessee_last_name', models.CharField(max_length=128)),
                ('lessee_passport_seria', models.CharField(max_length=128)),
                ('lessee_birth_date', models.CharField(blank=True, max_length=128, null=True)),
                ('lessee_phone_one', models.CharField(max_length=128)),
                ('lessee_phone_two', models.CharField(blank=True, max_length=128, null=True)),
                ('lessee_adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LesseeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.carslessee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField()),
                ('month_payment', models.CharField(max_length=256)),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.carslessee')),
            ],
        ),
        migrations.CreateModel(
            name='RentalConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('starting_price', models.CharField(max_length=256)),
                ('monthly_payment', models.CharField(max_length=258)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cars')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.carslessee')),
            ],
        ),
        migrations.RenameModel(
            old_name='Bot_user',
            new_name='BotUser',
        ),
        migrations.DeleteModel(
            name='Cars_lessee',
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rentalconditions'),
        ),
    ]
