# Generated by Django 4.1.7 on 2023-04-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_carimg_carslessee_lesseeimg_monthlypayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carslessee',
            name='lessee_adress',
        ),
        migrations.RemoveField(
            model_name='carslessee',
            name='lessee_birth_date',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='rental',
        ),
        migrations.AddField(
            model_name='carslessee',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carslessee',
            name='end_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carslessee',
            name='monthly_payment',
            field=models.CharField(default=1, max_length=258, verbose_name='Oylik tulov'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carslessee',
            name='start_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carslessee',
            name='starting_price',
            field=models.CharField(default=1, max_length=256, verbose_name='Boshlangich summa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carslessee',
            name='lessee_first_name',
            field=models.CharField(max_length=128, verbose_name='Ijarachi Ismi'),
        ),
        migrations.AlterField(
            model_name='carslessee',
            name='lessee_last_name',
            field=models.CharField(max_length=128, verbose_name='Ijarachi Familiyasi'),
        ),
        migrations.AlterField(
            model_name='carslessee',
            name='lessee_passport_seria',
            field=models.CharField(max_length=128, verbose_name='Passport raqami'),
        ),
        migrations.AlterField(
            model_name='carslessee',
            name='lessee_phone_one',
            field=models.CharField(max_length=128, verbose_name='Assosiy telefon'),
        ),
        migrations.AlterField(
            model_name='carslessee',
            name='lessee_phone_two',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Qo'shimcha telefon"),
        ),
        migrations.DeleteModel(
            name='RentalConditions',
        ),
    ]
