# Generated by Django 4.1.7 on 2023-04-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_carslessee_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslessee',
            name='end_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carslessee',
            name='start_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
